config/routes.rb
Rails.application.routes.draw do

  get 'schedule/add'

  devise_for :users, path: "accounts"

  resources :users do
    resources :reservations
  end

  resources :seminars do
    resources :attendees
  end

  patch '/users/:user_id/schedule/:seminar_id' => 'reservations#add', as: :add_seminar
  put   '/users/:user_id/schedule/:seminar_id' => 'reservations#add'

  get 'welcome' => 'welcome#index'
  get 'about' => 'about#index'

  root 'welcome#index'

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  belongs_to :seminar

  validates :user_id, uniqueness: { scope: :seminar_id }, presence: true
  validates :seminar, presence: true
end

app/models/seminar.rb
class Seminar < ActiveRecord::Base
  # associations
  has_many :reservations
  has_many :users, through: :reservations
  belongs_to :host, class_name: "User"

  validates_presence_of :title
  validates :starts_at, presence: true
  validates_presence_of :host
  validates_presence_of :capacity

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # data validations
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
                    length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }

  # associations
  has_many :reservations
  has_many :seminars, -> { order 'seminars.starts_at' },through: :reservations
  has_many :hosted_seminars, class_name: "Seminar"

  def reserved?(seminar)
    self.seminars.include? seminar
  end

  def host?(seminar)
    seminar.host.eql? self
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  def index
    @seminar = Seminar.find(attendee_params[:seminar_id])
    @attendees = @seminar.users
  end

  private
  def attendee_params
    params.permit(:seminar_id)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @user = User.find(reservation_params[:user_id])
    @reservations = @user.reservations
    @seminars = @user.seminars.order(:starts_at)
  end
  def create
    @seminar = Seminar.find(reservation_params[:seminar_id])
    reservation = Reservation.new(reservation_params)
    reservation.save

    flash[:notice] = "You are registered."
    redirect_to @seminar
  end

  def destroy
    @user = User.find(reservation_params[:user_id])
    @reservation = Reservation.find(reservation_params[:id])
    @reservation.destroy
    redirect_to user_reservations_path(@user)
  end

  private

  def reservation_params
    params.permit(:user_id, :seminar_id, :id)
  end
end

app/controllers/seminars_controller.rb
class SeminarsController < ApplicationController
  def index
    @seminars = Seminar.order(:starts_at)
  end

  def show
    @seminar = Seminar.find(params[:id])
  end

  def edit
    @seminar = Seminar.find(params[:id])
  end

  def update
    @seminar = Seminar.find(params[:id])
    @seminar.host ||= current_user
    if @seminar.update(seminar_params)
      redirect_to @seminar
    else
      render :edit
    end
  end

  def new
    @seminar = Seminar.new
  end

  def create
    @seminar = Seminar.new(seminar_params)
    @seminar.host = current_user
    if @seminar.save
      redirect_to @seminar
    else
      render :new
    end
  end

  private
  def seminar_params
    params.require(:seminar).
      permit(:title, :description, :tutor, :conference_url, :starts_at, :capacity)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/schedule_helper.rb
module ScheduleHelper
end

app/helpers/seminars_helper.rb
module SeminarsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.erb
  <h2>About Me</h2>
    <div id="profile">
    <p>I'm Jim Berrettini, an experienced software development director who's passionate about
      education, and about homeschooling and great books in particular.</p>
    <p>I have
      management, architecture, and development experience at firms in Internet,
      media and retail industries. I've done software development and project
      management, built teams that value self-development and collaboration.</p>

  </div>
  <h2>Things I'm Jazzed About</h2>
  <div id="enthusiasms">
    <ul>
      <li>Great Books</li>
      <li><a href="https://www.khanacademy.org/">Khan Academy</a></li>
      <li><a href="http://www.sjc.edu/">St. John's College</a></li>
      <li><a href="http://www.conversera.com/">Conversera</a></li>
    </ul>
  </div>
  <h2>My Experience</h2>
  <div id="experience">
    <ul>
      <li>Ralph Lauren, Interactive Development</li>
      <li>Time Inc, Internet Application Development</li>
      <li>Jive Software, Professional Services</li>
      <li>iVillage, Application Development</li>
      <li>AT&amp;T Downtown Digital, Software Development</li>
      <li>Magnet Interactive Studio, Multimedia Development</li>
      <li>Eidolon, Software Development</li>
    </ul>
  </div>
  <h2>Web Technologies</h2>
  <div id="skills">
    <ul>
      <li>Agile Development</li>
      <li>Ruby</li>
      <li>Java EE</li>
      <li>Javascript</li>
      <li>SQL</li>
      <li>HTTP</li>
      <li>HTML</li>
      <li>CSS</li>
    </ul>
  </div>
  <%# <h2>Contact</h2>
  <div id="contact">
    <ul>
      <li><a href="mailto:james.berrettini@me.com">james.berrettini@me.com</a></li>
    </ul>
  </div> %>

app/views/attendees/index.html.erb
<h1>Attendees for <%= @seminar.title %></h1>

<p>
  <ul>
    <% @attendees.each do |attendee| %>
    <li><%= attendee.name %></li>
    <% end %>
  </ul>
</p>

app/views/layouts/_auth_links.html.erb
<%# add authentication links to this file %>
<% if user_signed_in? %>
<li class="active">
<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
</li>
<% else %>
<li class="active">
<%= link_to('Login', new_user_session_path)  %>
</li>
<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul class="right">
      <%= render "layouts/auth_links" %>
    </ul>
    <ul class="left">
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li class="has-dropdown"><%= link_to 'Seminars', { controller: "/seminars", action: "index" } %>
  <ul class="dropdown">
    <li><%= link_to 'Show All Seminars', { controller: "/seminars", action: "index" } %></li>
    <% if user_signed_in? %>
    <li>
      <%= link_to(current_user.name + "'s Seminars", user_reservations_path(current_user))  %>
    </li>
    <% end %>
  </ul>
</li>
<li><%= link_to 'About', { controller: "/about", action: "index" } %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Do You Read Me?" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Doyoureadme" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>
    <%# debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/reservations/add.html.erb
<h1>Reservation#add</h1>
<p>Find me in app/views/reservation/add.html.erb</p>
<p>User: <%= @user.name %>, Seminar: <%= @seminar.title %></p>

app/views/reservations/index.html.erb
<h2>Reservations</h2>
<ul>
  <% @reservations.each do |reservation|
       seminar = reservation.seminar
    %>
  <li><strong><%= link_to seminar.title, seminar %></strong> led by <%= seminar.tutor %>
    at <%= seminar.starts_at %>.
    <%= link_to "Cancel",
                                     user_reservation_path(@user, reservation),
                                     method: :delete %>
  </li>
  <% end %>
</ul>

app/views/seminars/_form.html.erb
<%= form_for @seminar do |f| %>
<fieldset>
<% if @seminar.errors.count > 0 %>
<small class="error"><%= @seminar.errors.full_messages.to_sentence %></small>
<% end %>
<p>
  <%= f.label :title %><br/>
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :description %><br/>
  <%= f.text_area :description, rows: 5 %>
</p>
<p>
  <%= f.label :tutor %><br/>
  <%= f.text_field :tutor %>
</p>
<p>
  <%= f.label :conference_url, "Conference URL" %><br/>
  <%= f.text_field :conference_url %>
</p>
<p>
  <%= f.label :starts_at %><br/>
  <%= f.datetime_local_field :starts_at %>
</p>
<p>
  <%= f.label :capacity %><br/>
  <%= f.number_field :capacity, in: 2..20 %>
</p>
<p>
  <%= f.submit %>
</p>
</fieldset>
<% end %>

app/views/seminars/edit.html.erb
<h1>Editing Seminar: <%= @seminar.title %></h1>
<%= render 'form' %>

app/views/seminars/index.html.erb
<h1>Seminars</h1>
<ul>
  <% @seminars.each do |seminar| %>
  <li><strong><%= link_to seminar.title, seminar %></strong> led by <%= seminar.tutor %>
    at <%= seminar.starts_at %>.</li>
  <% end %>
</ul>
<% if user_signed_in? %>
<%= link_to 'Add New Seminar', new_seminar_path %>
<% end %>

app/views/seminars/new.html.erb
<h1>Create Seminar</h1>
<%= render 'form' %>

app/views/seminars/show.html.erb
<article>
  <h2><%= @seminar.title %> </h2>
  <% if user_signed_in? %>
    <% if current_user.host? @seminar %>
      <%= link_to "Edit", edit_seminar_path(@seminar)%><br/>
      <%= link_to "Delete", seminar_path(@seminar), method: :delete %>
    <% end %>
    <%#link_to "Add to My Seminars", user_reservations_path(current_user, @seminar),
           method: :post %>
    <% unless current_user.reserved? @seminar %>
      <%= form_for current_user.reservations.build, url: user_reservations_path(current_user) do |f| %>
      <%= hidden_field_tag :seminar_id, @seminar.id  %>
      <%= f.submit "Add to My Seminars"%>
      <% end %>
    <% else %>
    <%= link_to "Cancel Reservation", user_reservation_path(current_user, Reservation.where(user: current_user,
                                                                                seminar: @seminar).take!),
                method: :delete %>
    <% end %>
  <% end %>
  <p>
    <ul>
      <li>Tutor: <%= @seminar.tutor%></li>
      <li>Starts: <%= @seminar.starts_at %> </li>
      <li>Conference URL: <%= link_to @seminar.conference_url, @seminar.conference_url,
                              target: "_blank" %></li>
      <li>Capacity: <%= @seminar.capacity %></li>
      <li>Seats remaining: <%= @seminar.capacity - @seminar.reservations.count %></li>
    </ul>
  </p>
  <h3>Description</h3>
  <p><%= @seminar.description %></p>
</article>

<%# <%= link_to "All Seminars", seminars_path %>

app/views/welcome/index.html.erb
<h1>Welcome to <em>Do You Read Me?</em></h1>
<p>Do You Read Me? is a Web site dedicated to growing a community of co-learners who
  strive to experience beautiful things by reading great books together. Its goals are
  to facilitate great conversations by
  <ul>
    <li>fostering a culture of listening, thoughtfulness, and respect;</li>
    <li>training ourselves in the practices necessary to promote such a culture; and</li>
    <li>providing organizational tools to make great conversations accessible everywhere.</li>
  </ul>
</p>